name: Expense Control Api
run-name: Expense Control Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [ main, development]

permissions:
  contents: write
  actions: write
  security-events: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yml
    with:
      path: .
      project: ExpenseControl.API
      test: ExpenseControl.Test
      product: Expense-Control
      service-name: Expense-Control-Api
      destroy: false
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
