name: Workflow
on:
  workflow_call:
    inputs:
      product:
        description: 'The name of product passed form the caller workflow'
        required: true
        type: string
      path:
        description: 'The path passed from the caller workflow'
        required: true
        type: string
      project:
        description: 'The project passed from the caller workflow'
        required: true
        type: string
      test:
        description: 'The test path passed from the caller workflow'
        required: true
        type: string
      service-name:
        description: 'The service name passed from the caller workflow'
        required: true
        type: string
      destroy:
        description: 'The terraform destroy passed from the caller workflow'
        required: true
        type: boolean
    secrets:
      PIPELINE_TOKEN:
        description: 'The pipeline token passed from the caller workflow'
        required: true
      AWS_REGION:
        description: 'AWS_REGION'
        required: true
      AWS_ROLE:
        description: 'AWS_ROLE'
        required: true
      CODACY_PROJECT_TOKEN:
        description: 'CODACY_PROJECT_TOKEN'
        required: true
      AWS_ACCESS_KEY_ID:
        description: 'The AWS access key id'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'The AWS secret access key'
        required: true
      CONNECTION_STRING:
        description: 'Database connection string'
        required: true
      JWT_TOKEN:
        description: 'The JWT Token for api authentication'
        required: true

permissions:
  contents: write
  actions: write
  security-events: write
  issues: write
  pull-requests: write
  id-token: write

concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    uses: ./.github/workflows/_build.yml
    with:
      project: ./${{ inputs.path }}/${{ inputs.project }}
  test:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    needs: [ build ]
    uses: ./.github/workflows/_test.yml
    with:
      test: ./${{ inputs.test }}
      project: ${{ inputs.project }}
    secrets: inherit
  quality:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    needs: [ test ]
    uses: ./.github/workflows/_quality.yml
    with:
      project: $GITHUB_WORKSPACE/${{ inputs.project }}
    secrets: inherit
  #security:
  #  if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
  #  needs: [ quality ]
  #  uses: ./.github/workflows/_security.yml
  #  with:
  #    path: ./${{ inputs.path }}
  #    project: ${{ inputs.project }}
  #  secrets: inherit
  deploy:
    needs: [ quality ]
    uses: ./.github/workflows/_deploy.yml
    with:
      project: ${{ inputs.project }}
    secrets: inherit